from __future__ import annotations

from enum import Enum


class SessionState(str, Enum):
    CREATED = "CREATED"
    INPUT_VALIDATING = "INPUT_VALIDATING"
    PATIENT_EXTRACTING = "PATIENT_EXTRACTING"
    RETRIEVING = "RETRIEVING"
    CANDIDATES_READY = "CANDIDATES_READY"
    COMPILING = "COMPILING"
    EVALUATING = "EVALUATING"
    VERIFYING = "VERIFYING"
    RANKING = "RANKING"
    QUESTION_SELECTING = "QUESTION_SELECTING"
    QUESTION_READY = "QUESTION_READY"
    ANSWER_INTERPRETING = "ANSWER_INTERPRETING"
    REEVALUATING = "REEVALUATING"
    COMPLETE = "COMPLETE"
    DEGRADED = "DEGRADED"
    FAILED = "FAILED"
    RESET = "RESET"
